import type { Metadata } from "next";
import {
    Inter as font_header,
    Newsreader as font_sans,
    Cascadia_Mono as font_mono,
} from "next/font/google";
import "./globals.css";
import { CustomThemeProvider } from "@/components/theme/c_theme-provider";
import { Toaster } from "sonner";

const fontHeader = font_header({
    variable: "--font-font-header",
    subsets: ["latin"],
});

const fontSans = font_sans({
    variable: "--font-font-sans",
    subsets: ["latin"],
});

const fontMono = font_mono({
    variable: "--font-font-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Find-A-Friend",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${fontSans.variable} ${fontMono.variable} ${fontHeader.variable} antialiased bg-[#D1F0CA] dark:bg-[#081e03]`}
            >
                <CustomThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    {children}
                    <Toaster />
                </CustomThemeProvider>
            </body>
        </html>
    );
}
